### ISSUE TITLE
ImportError: No module named python

### ISSUE THREAD

**Issue by Jonathanyu2014** [ushaham/BatchEffectRemoval2018#1]
When I run python calibrate.py, something wrong happens as follows.  

Traceback (most recent call last):
  File "/home/PUB/softwares/BatchEffectRemoval2018/calibrate.py", line 18, in <module>
    import tensorflow as tf
  File "/home/PUB/softwares/Anaconda2-4.3.0/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
ImportError: No module named python

**Comment by ushaham** [comment]
Do you have tensor flow installed? The code was written for Tensorflow 3.6

**Comment by Jonathanyu2014** [comment]
The problem has been solved. I re-installed tensorflow in python3.6. Thanks.
